### PR TITLE
Theme update for the SDK matching it with EventDiscovery SDK. Refacto…

### PR DESCRIPTION
**Pull request by lemonboston**
…r and cleanup around styles. #3 

---

Notes:

The shadow for the toolbar on the event preview screen is a fix View in the layout now, so in the collapsed state it's a 'double' shadow. The case in ED SDK is a bit different because there the expanded state doesn't have the shadow. So I thought it's best to figure it out in a separate ticket: https://github.com/schedjoules/android-public-calendars-sdk/issues/19
(If you happen to know the solution from the top of you head please comment on the ticket)

I've removed a lot of unused, obsolete styles, but kept all the text styles, just renamed them. In general, I tried to not change anything, like sizes, colors, etc, besides the theme and the color of some element (calendary sync switch, favorite star icon, settings icon there).
These text styles could perhaps be further consolidated later but I didn't consider it important now.

UI glitch bug: when the calendar sync switch is tapped, the favorite star icon moves a little bit: https://github.com/schedjoules/android-public-calendars-sdk/issues/20

The colors of the welcome wizard top and bottom part is an open question.

### CODE REVIEW

**Comment by dmfs** [comment]
We've decided to omit the intro for now. It's not finalized and hasn't been published so far anyway. Please just disable it.

**Comment by dmfs** [comment]
The icons of the details view should use the accent color.

**Comment by lemonboston** [comment]
Disabled the intro screen and updated the details icon to have accent color.

**Comment by lemonboston** [comment]
A small note, that the tinting of the TextView compound drawable is implemented as a private method now.
It could be a `SmartView`, like `new TintableCompoundDrawable(textView).update(color)` or something like that. Let me know if I should update. `SmartView` is not yet in the project.

**Review by dmfs — APPROVED** [review]

**Pull request merged**
